// Connection guidance from the pinned CodexBar docs; refresh alongside the dependency.
import Foundation

enum ExtendedProviderGuides {
    static let all: [String: ExtendedProviderGuide] = [
        "codex": .init(document: "codex.md", summary: "Codex provider data sources: OpenAI web dashboard, Codex CLI RPC, credits, and local cost usage.", environmentKeys: ["XDG_DATA_HOME"]),
        "openai": .init(document: "openai.md", summary: "OpenAI API provider: Admin API key usage/cost graphs and legacy balance fallback.", environmentKeys: ["OPENAI_ADMIN_KEY", "OPENAI_API_KEY", "OPENAI_PROJECT_ID"]),
        "azureopenai": .init(document: "azure-openai.md", summary: "Azure OpenAI provider: API key, endpoint, and deployment validation probe.", environmentKeys: ["AZURE_OPENAI_API_KEY", "AZURE_OPENAI_API_VERSION", "AZURE_OPENAI_DEPLOYMENT_NAME", "AZURE_OPENAI_ENDPOINT"]),
        "claude": .init(document: "claude.md", summary: "Claude provider data sources: OAuth API, web API (cookies), CLI PTY, and local cost usage.", environmentKeys: ["ANTHROPIC_ADMIN_KEY", "CLAUDE_CONFIG_DIR"]),
        "clinepass": .init(document: "providers.md", summary: "Provider data sources and parsing overview for every registered CodexBar provider.", environmentKeys: []),
        "cursor": .init(document: "cursor.md", summary: "Cursor provider data sources, external-browser account switching, and cursor.com APIs.", environmentKeys: ["XDG_DATA_HOME"]),
        "opencode": .init(document: "opencode.md", summary: "OpenCode provider notes: browser cookies, local SQLite usage, and parsing.", environmentKeys: ["CODEXBAR_OPENCODE_WORKSPACE_ID", "OPENCODE_API_KEY"]),
        "opencodego": .init(document: "opencode.md", summary: "OpenCode provider notes: browser cookies, local SQLite usage, and parsing.", environmentKeys: ["CODEXBAR_OPENCODE_WORKSPACE_ID", "OPENCODE_API_KEY"]),
        "alibaba": .init(document: "alibaba-coding-plan.md", summary: "Use a Model Studio/Bailian browser session or manual Cookie header. API-key access depends on account and region.", environmentKeys: ["ALIBABA_CODING_PLAN_API_KEY", "ALIBABA_QWEN_API_KEY", "DASHSCOPE_API_KEY", "ALIBABA_CODING_PLAN_COOKIE", "ALIBABA_CODING_PLAN_HOST", "ALIBABA_CODING_PLAN_QUOTA_URL", "ALIBABA_CODING_PLAN_REQUIRE_PROVIDER_ENDPOINT_OVERRIDES"]),
        "alibabatokenplan": .init(document: "alibaba-token-plan.md", summary: "Alibaba Token Plan provider notes: Team and Personal/Solo variants, Bailian CLI/browser auth, and setup.", environmentKeys: ["ALIBABA_TOKEN_PLAN_HOST", "ALIBABA_TOKEN_PLAN_QUOTA_URL"]),
        "qwencloud": .init(document: "qwen-cloud.md", summary: "Qwen Cloud provider notes: cookie auth, 5-hour and weekly token-plan usage, and setup.", environmentKeys: ["QWEN_CLOUD_COOKIE", "QWEN_CLOUD_HOST", "QWEN_CLOUD_QUOTA_URL"]),
        "factory": .init(document: "factory.md", summary: "Factory (Droid) provider data sources: API key, browser cookies, WorkOS tokens, and Factory APIs.", environmentKeys: ["FACTORY_API_KEY"]),
        "fireworks": .init(document: "fireworks.md", summary: "Fireworks provider data sources: API key account discovery and the 30-day spend billing summary.", environmentKeys: ["FIREWORKS_ACCOUNT_SLUG", "FIREWORKS_API_KEY", "FIREWORKS_KEY"]),
        "gemini": .init(document: "gemini.md", summary: "Gemini provider data sources: OAuth-backed quota APIs, token refresh, and tier detection.", environmentKeys: ["GEMINI_OAUTH2_JS_PATH", "GEMINI_OAUTH_CLIENT_ID", "GEMINI_OAUTH_CLIENT_SECRET"]),
        "antigravity": .init(document: "antigravity.md", summary: "Antigravity provider notes: OAuth usage, multi-account switching, local LSP probing, and quota parsing.", environmentKeys: ["ANTIGRAVITY_CLI_PATH", "ANTIGRAVITY_OAUTH_CLIENT_ID", "ANTIGRAVITY_OAUTH_CLIENT_SECRET", "ANTIGRAVITY_OAUTH_CREDENTIALS_JSON", "GEMINI_CLI_HOME", "TOKSCALE_CONFIG_DIR"]),
        "copilot": .init(document: "copilot.md", summary: "Copilot provider data sources: GitHub device flow, Copilot internal usage API, and optional GitHub web budgets.", environmentKeys: []),
        "devin": .init(document: "devin.md", summary: "Devin provider auth, quota endpoint, and setup.", environmentKeys: ["DEVIN_AUTHORIZATION", "DEVIN_BEARER_TOKEN", "DEVIN_ORG", "DEVIN_ORGANIZATION"]),
        "zai": .init(document: "zai.md", summary: "z.ai / GLM provider data sources, regions, and Coding Plan quota mapping.", environmentKeys: ["BIGMODEL_API_KEY", "CODEXBAR_CONFIG", "GLM_API_KEY", "ZHIPUAI_API_KEY", "ZHIPU_API_KEY", "Z_AI_API_HOST", "Z_AI_API_KEY", "Z_AI_QUOTA_URL"]),
        "minimax": .init(document: "minimax.md", summary: "MiniMax provider data sources: Coding Plan tokens, browser cookies, and web-session parsing.", environmentKeys: ["MINIMAX_API_KEY", "MINIMAX_CODING_API_KEY", "MINIMAX_CODING_PLAN_URL", "MINIMAX_COOKIE", "MINIMAX_COOKIE_HEADER", "MINIMAX_HOST", "MINIMAX_REMAINS_URL", "MINIMAX_REQUIRE_PROVIDER_ENDPOINT_OVERRIDES"]),
        "manus": .init(document: "manus.md", summary: "Manus provider: browser session_id cookie auth for credit balance, monthly credits, and daily refresh tracking.", environmentKeys: ["MANUS_COOKIE", "MANUS_SESSION_TOKEN"]),
        "kimi": .init(document: "kimi.md", summary: "Kimi provider notes: cookie auth, quotas, and rate-limit parsing.", environmentKeys: ["KIMI_AUTH_TOKEN", "KIMI_CODE_API_KEY", "KIMI_CODE_BASE_URL", "KIMI_CODE_HOME", "KIMI_CODE_OAUTH_HOST", "KIMI_OAUTH_HOST"]),
        "kilo": .init(document: "kilo.md", summary: "Kilo provider data sources: app.kilo.ai API token and CLI auth-file fallback.", environmentKeys: ["KILO_API_KEY"]),
        "kiro": .init(document: "kiro.md", summary: "Kiro provider data sources: CLI-based usage via kiro-cli /usage, enriched with GetUsageLimits for overage.", environmentKeys: []),
        "vertexai": .init(document: "vertexai.md", summary: "Vertex AI provider data sources: gcloud ADC credentials and Cloud Monitoring quota usage.", environmentKeys: ["CLOUDSDK_CORE_PROJECT", "GCLOUD_PROJECT", "GOOGLE_CLOUD_PROJECT"]),
        "augment": .init(document: "augment.md", summary: "Augment provider notes: cookie auth, keepalive, and credits parsing.", environmentKeys: []),
        "jetbrains": .init(document: "jetbrains.md", summary: "JetBrains AI provider notes: local XML quota parsing, IDE auto-detection, and UI mapping.", environmentKeys: ["IDE_BASE"]),
        "moonshot": .init(document: "moonshot.md", summary: "Moonshot / Kimi Open Platform data sources, regional key routing, and balance endpoint.", environmentKeys: ["MOONSHOT_API_KEY", "MOONSHOT_KEY", "MOONSHOT_REGION"]),
        "amp": .init(document: "amp.md", summary: "Amp provider notes: CLI usage, web fallback, cookie auth, and credits.", environmentKeys: ["AMP_API_KEY"]),
        "t3chat": .init(document: "t3chat.md", summary: "T3 Chat provider auth, tRPC endpoint, and quota windows.", environmentKeys: []),
        "ollama": .init(document: "ollama.md", summary: "Ollama provider notes: API key auth, settings scrape, cookie auth, and Cloud Usage parsing.", environmentKeys: ["OLLAMA_API_KEY"]),
        "synthetic": .init(document: "synthetic.md", summary: "Synthetic provider data sources: API key quota endpoint and usage lanes.", environmentKeys: ["SYNTHETIC_API_KEY"]),
        "openrouter": .init(document: "openrouter.md", summary: "OpenRouter provider: API key credits, rate limits, and daily/weekly/monthly spend.", environmentKeys: ["OPENROUTER_API_KEY", "OPENROUTER_API_URL", "OPENROUTER_HTTP_REFERER", "OPENROUTER_MANAGEMENT_API_KEY", "OPENROUTER_X_TITLE"]),
        "elevenlabs": .init(document: "elevenlabs.md", summary: "ElevenLabs provider notes: API key setup and subscription usage fields.", environmentKeys: ["ELEVENLABS_API_KEY", "ELEVENLABS_API_URL", "XI_API_KEY"]),
        "warp": .init(document: "warp.md", summary: "Warp provider notes: API token setup and request limit parsing.", environmentKeys: ["WARP_API_KEY", "WARP_TOKEN"]),
        "windsurf": .init(document: "windsurf.md", summary: "Windsurf provider data sources: browser localStorage session import, local SQLite cache, and GetPlanStatus protobuf API.", environmentKeys: []),
        "zed": .init(document: "zed.md", summary: "Zed provider data source: editor Keychain session and Zed cloud API.", environmentKeys: []),
        "perplexity": .init(document: "perplexity.md", summary: "Perplexity provider: browser cookie setup, credits API, recurring/bonus/purchased credit display.", environmentKeys: ["PERPLEXITY_COOKIE", "PERPLEXITY_SESSION_TOKEN"]),
        "mimo": .init(document: "mimo.md", summary: "Xiaomi MiMo provider notes: cookie auth, balance endpoint, and setup.", environmentKeys: ["MIMO_API_URL", "MIMO_LOCAL_USAGE_PATH"]),
        "doubao": .init(document: "doubao.md", summary: "Doubao provider notes: arkcli plan usage, API-key auth, and Volcengine Ark request limits.", environmentKeys: ["ARKCLI_PATH", "ARK_API_KEY", "DOUBAO_API_KEY", "VOLCENGINE_API_KEY"]),
        "sakana": .init(document: "sakana.md", summary: "Sakana AI provider: manual Cookie header, billing page parser, 5-hour/weekly quota windows, and pay-as-you-go credit balance.", environmentKeys: ["SAKANA_COOKIE"]),
        "abacus": .init(document: "abacus.md", summary: "Abacus AI provider: browser cookie auth for ChatLLM/RouteLLM compute credit tracking.", environmentKeys: []),
        "mistral": .init(document: "mistral.md", summary: "Mistral provider: browser cookie setup, billing usage, credit balance, and Vibe monthly-plan usage.", environmentKeys: []),
        "deepseek": .init(document: "deepseek.md", summary: "DeepSeek provider data sources: API key, balance, and optional detailed usage endpoints.", environmentKeys: ["DEEPSEEK_API_KEY", "DEEPSEEK_KEY", "DEEPSEEK_PLATFORM_TOKEN", "DEEPSEEK_USER_TOKEN"]),
        "deepinfra": .init(document: "deepinfra.md", summary: "DeepInfra provider setup, API-key billing queries, and balance/spend display.", environmentKeys: ["DEEPINFRA_API_KEY", "DEEPINFRA_TOKEN"]),
        "codebuff": .init(document: "codebuff.md", summary: "Codebuff provider data sources: API token, CLI credentials file, credit balance, and weekly rate limits.", environmentKeys: ["CODEBUFF_API_KEY", "CODEBUFF_API_URL"]),
        "crof": .init(document: "crof.md", summary: "Crof provider data source: API key + usage_api credit balance and optional request quota.", environmentKeys: ["CROFAI_API_KEY", "CROF_API_KEY"]),
        "venice": .init(document: "venice.md", summary: "Venice provider setup, API-key balance query, and DIEM/USD balance display.", environmentKeys: ["VENICE_API_KEY", "VENICE_KEY"]),
        "commandcode": .init(document: "command-code.md", summary: "Command Code provider notes: cookie authentication and usage-window parsing.", environmentKeys: ["COMMANDCODE_API_URL"]),
        "qoder": .init(document: "qoder.md", summary: "Qoder provider: browser/manual cookie setup for big model credit usage on qoder.com and qoder.com.cn.", environmentKeys: []),
        "stepfun": .init(document: "stepfun.md", summary: "StepFun provider data sources: username + password login for Step Plan rate limits and subscription plan name.", environmentKeys: ["STEPFUN_PASSWORD", "STEPFUN_TOKEN", "STEPFUN_USERNAME"]),
        "bedrock": .init(document: "bedrock.md", summary: "AWS Bedrock provider: Cost Explorer spend, CloudWatch Claude activity, credentials, and budgets.", environmentKeys: ["AWS_ACCESS_KEY_ID", "AWS_CLI_PATH", "AWS_DEFAULT_REGION", "AWS_PROFILE", "AWS_REGION", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN", "CODEXBAR_BEDROCK_API_URL", "CODEXBAR_BEDROCK_AUTH_MODE", "CODEXBAR_BEDROCK_BUDGET", "CODEXBAR_BEDROCK_CLOUDWATCH_API_URL"]),
        "grok": .init(document: "grok.md", summary: "Grok provider data sources: ACP JSON-RPC, CLI-proxy and grok.com billing fallbacks, OAuth credentials, and local session signals.", environmentKeys: ["CODEXBAR_ALLOW_BROWSER_COOKIE_IMPORT", "GROK_HOME", "GROK_OAUTH_TOKEN"]),
        "groq": .init(document: "groq.md", summary: "Groq provider: console spend/usage via the browser session (Stytch), with an optional Enterprise Prometheus fallback.", environmentKeys: ["GROQ_API_KEY", "GROQ_SESSION_JWT", "GROQ_SESSION_TOKEN", "GROQ_STYTCH_PUBLIC_TOKEN", "GROQ_STYTCH_URL"]),
        "llmproxy": .init(document: "llm-proxy.md", summary: "LLM Proxy provider setup and quota-stats usage source.", environmentKeys: ["LLM_PROXY_API_KEY", "LLM_PROXY_BASE_URL"]),
        "litellm": .init(document: "litellm.md", summary: "LiteLLM provider setup and usage data shape.", environmentKeys: ["LITELLM_API_KEY", "LITELLM_BASE_URL"]),
        "deepgram": .init(document: "deepgram.md", summary: "Deepgram provider: API key setup, project discovery, and usage-breakdown metrics.", environmentKeys: ["DEEPGRAM_API_KEY", "DEEPGRAM_API_URL", "DEEPGRAM_PROJECT_ID"]),
        "poe": .init(document: "poe.md", summary: "Poe provider: API key setup, point balance, and recent usage history.", environmentKeys: ["POE_API_KEY"]),
        "chutes": .init(document: "chutes.md", summary: "Chutes provider: API key setup, subscription usage, and quota windows.", environmentKeys: ["CHUTES_API_KEY", "CHUTES_API_URL"]),
        "neuralwatt": .init(document: "neuralwatt.md", summary: "Neuralwatt provider notes: API key setup and quota usage fields.", environmentKeys: ["NEURALWATT_API_KEY", "NEURALWATT_API_URL"]),
        "clawrouter": .init(document: "clawrouter.md", summary: "ClawRouter setup for monthly budget, spend, and routed-provider usage.", environmentKeys: ["CLAWROUTER_API_KEY", "CLAWROUTER_BASE_URL"]),
        "longcat": .init(document: "longcat.md", summary: "LongCat provider cookie sources, quota requests, and snapshot mapping.", environmentKeys: ["LONGCAT_MANUAL_COOKIE"]),
        "sub2api": .init(document: "sub2api.md", summary: "sub2api setup for group API-key quota, subscription usage, and wallet balance.", environmentKeys: ["SUB2API_API_KEY", "SUB2API_BASE_URL"]),
        "wayfinder": .init(document: "wayfinder.md", summary: "Wayfinder setup for local gateway health, per-route breakdown, and savings.", environmentKeys: ["WAYFINDER_GATEWAY_URL"]),
        "zenmux": .init(document: "zenmux.md", summary: "ZenMux provider: Management API key setup, rolling quota windows, and PAYG balance.", environmentKeys: ["ZENMUX_MANAGEMENT_API_KEY"]),
        "aiand": .init(document: "aiand.md", summary: "ai& provider: API key setup and 30-day spend summed from the request logs API.", environmentKeys: ["AIAND_API_KEY"]),
        "zoommate": .init(document: "zoommate.md", summary: "ZoomMate provider auth, credits endpoint, history/pacing, and status page.", environmentKeys: []),
        "xai": .init(document: "xai.md", summary: "xAI provider: Management API key + team ID setup, prepaid balance, and daily platform spend.", environmentKeys: ["XAI_MANAGEMENT_API_KEY", "XAI_TEAM_ID"]),
        "notion": .init(document: "notion.md", summary: "Notion AI provider auth, usage endpoint, and allowance windows.", environmentKeys: []),
        "ibmbob": .init(document: "ibm-bob.md", summary: "IBM Bob authentication and Bobcoin usage tracking.", environmentKeys: ["BOBSHELL_API_KEY"]),
    ]
}
