import Foundation
import CodexBarCore

/// Match public error types; response text may contain secrets and is never parsed or displayed.
enum ExtendedProviderFailureClassifier {
    static func status(for error: Error, provider: String) -> ProviderStatus? {
        let permissions = ProviderStatus.unsupported("\(provider) denied access. Check the API key permissions, endpoint and required plan in provider settings.")
        if let classified = error as? ProviderFetchClassifiedError {
            switch classified.kind {
            case .authenticationExpired, .missingCredential: return .needsAuth
            case .permissionDenied: return permissions
            default: return nil
            }
        }
        switch error {
        case is ProviderFetchError:
            return .needsAuth
        case CodexBarCore.AbacusUsageError.noSessionCookie,
             CodexBarCore.AbacusUsageError.sessionExpired,
             CodexBarCore.AbacusUsageError.unauthorized,
             CodexBarCore.AiAndUsageError.notConfigured,
             CodexBarCore.AiAndUsageError.authenticationRejected,
             CodexBarCore.AlibabaCodingPlanSettingsError.missingToken,
             CodexBarCore.AlibabaCodingPlanSettingsError.missingCookie(_),
             CodexBarCore.AlibabaCodingPlanSettingsError.invalidCookie,
             CodexBarCore.AlibabaCodingPlanUsageError.loginRequired,
             CodexBarCore.AlibabaCodingPlanUsageError.invalidCredentials,
             CodexBarCore.AlibabaTokenPlanSettingsError.missingCookie(_),
             CodexBarCore.AlibabaTokenPlanSettingsError.invalidCookie,
             CodexBarCore.AlibabaTokenPlanUsageError.loginRequired,
             CodexBarCore.AlibabaTokenPlanUsageError.invalidCredentials,
             CodexBarCore.AmpUsageError.notLoggedIn,
             CodexBarCore.AmpUsageError.invalidCredentials,
             CodexBarCore.AmpUsageError.missingAPIToken,
             CodexBarCore.AmpUsageError.invalidAPIToken,
             CodexBarCore.AmpUsageError.noSessionCookie,
             CodexBarCore.AuggieCLIError.notAuthenticated,
             CodexBarCore.AugmentSessionKeepaliveError.sessionExpired,
             CodexBarCore.AugmentStatusProbeError.notLoggedIn,
             CodexBarCore.AugmentStatusProbeError.noSessionCookie,
             CodexBarCore.AugmentStatusProbeError.sessionExpired,
             CodexBarCore.AzureOpenAISettingsError.missingAPIKey,
             CodexBarCore.AzureOpenAIUsageError.missingAPIKey,
             CodexBarCore.BedrockUsageError.missingCredentials,
             CodexBarCore.BedrockUsageError.profileSessionExpired(_),
             CodexBarCore.ChutesSettingsError.missingToken,
             CodexBarCore.ChutesUsageError.missingCredentials,
             CodexBarCore.ChutesUsageError.invalidCredentials,
             CodexBarCore.CodebuffSettingsError.missingToken,
             CodexBarCore.CodebuffUsageError.missingCredentials,
             CodexBarCore.CodebuffUsageError.unauthorized,
             CodexBarCore.DeepInfraUsageError.missingCredentials,
             CodexBarCore.DeepSeekUsageError.missingCredentials,
             CodexBarCore.DeepSeekUsageError.invalidPlatformToken,
             CodexBarCore.DeepgramSettingsError.missingToken,
             CodexBarCore.DevinUsageError.noSession,
             CodexBarCore.DevinUsageError.invalidCredentials,
             CodexBarCore.DoubaoUsageError.missingCredentials,
             CodexBarCore.DoubaoUsageError.arkcliAuthenticationRequired,
             CodexBarCore.ElevenLabsUsageError.missingCredentials,
             CodexBarCore.ElevenLabsUsageError.invalidCredentials,
             CodexBarCore.ElevenLabsUsageError.authenticationFailed,
             CodexBarCore.FactoryStatusProbeError.notLoggedIn,
             CodexBarCore.FactoryStatusProbeError.missingAPIKey,
             CodexBarCore.FactoryStatusProbeError.unauthorizedAPIKey,
             CodexBarCore.FactoryStatusProbeError.noSessionCookie,
             CodexBarCore.FireworksUsageError.missingCredentials,
             CodexBarCore.FireworksUsageError.authenticationRejected,
             CodexBarCore.GeminiStatusProbeError.notLoggedIn,
             CodexBarCore.GroqConsoleError.invalidSession(_),
             CodexBarCore.GroqUsageError.missingCredentials,
             CodexBarCore.IBMBobUsageError.missingCredentials,
             CodexBarCore.IBMBobUsageError.invalidCredentials,
             CodexBarCore.KiloUsageError.missingCredentials,
             CodexBarCore.KiloUsageError.cliSessionMissing(_),
             CodexBarCore.KiloUsageError.cliSessionInvalid(_),
             CodexBarCore.KiloUsageError.unauthorized,
             CodexBarCore.KimiAPIError.missingToken,
             CodexBarCore.KimiAPIError.invalidToken,
             CodexBarCore.KimiAPIError.missingAPIKey,
             CodexBarCore.KimiAPIError.invalidAPIKey,
             CodexBarCore.KimiAPIError.expiredCodeCredential,
             CodexBarCore.KimiAPIError.invalidCodeCredential,
             CodexBarCore.KiroStatusProbeError.notLoggedIn,
             CodexBarCore.KiroUsageLimitsError.credentialsUnavailable(_),
             CodexBarCore.LLMProxyUsageError.missingCredentials,
             CodexBarCore.LiteLLMUsageError.missingCredentials,
             CodexBarCore.LongCatAPIError.missingCookies,
             CodexBarCore.LongCatAPIError.invalidSession,
             CodexBarCore.ManusAPIError.missingToken,
             CodexBarCore.ManusAPIError.invalidCookie,
             CodexBarCore.ManusAPIError.invalidToken,
             CodexBarCore.MiMoSettingsError.missingCookie(_),
             CodexBarCore.MiMoSettingsError.invalidCookie,
             CodexBarCore.MiMoUsageError.invalidCredentials,
             CodexBarCore.MiMoUsageError.loginRequired,
             CodexBarCore.MiniMaxAPISettingsError.missingToken,
             CodexBarCore.MiniMaxSettingsError.missingCookie,
             CodexBarCore.MiniMaxUsageError.invalidCredentials,
             CodexBarCore.MistralUsageError.missingCookie,
             CodexBarCore.MistralUsageError.invalidCredentials,
             CodexBarCore.MoonshotUsageError.missingCredentials,
             CodexBarCore.NeuralWattUsageError.missingCredentials,
             CodexBarCore.NotionUsageError.noSessionCookie,
             CodexBarCore.NotionUsageError.invalidCredentials,
             CodexBarCore.OpenAIAPICreditBalanceError.missingCredentials,
             CodexBarCore.OpenAIAPICreditBalanceError.unauthorized,
             CodexBarCore.OpenAIAPISettingsError.missingToken,
             CodexBarCore.OpenAIAPIUsageError.missingCredentials,
             CodexBarCore.OpenCodeUsageError.invalidCredentials,
             CodexBarCore.OpenRouterSettingsError.missingToken,
             CodexBarCore.PerplexityAPIError.missingToken,
             CodexBarCore.PerplexityAPIError.invalidCookie,
             CodexBarCore.PerplexityAPIError.invalidToken,
             CodexBarCore.QoderUsageError.missingCredentials,
             CodexBarCore.QoderUsageError.invalidCredentials,
             CodexBarCore.QwenCloudSettingsError.missingCookie(_),
             CodexBarCore.QwenCloudSettingsError.invalidCookie,
             CodexBarCore.QwenCloudUsageError.loginRequired,
             CodexBarCore.QwenCloudUsageError.invalidCredentials,
             CodexBarCore.SakanaUsageError.missingCookie,
             CodexBarCore.SakanaUsageError.loginRequired,
             CodexBarCore.StepFunUsageError.missingCredentials,
             CodexBarCore.StepFunUsageError.missingToken,
             CodexBarCore.SyntheticSettingsError.missingToken,
             CodexBarCore.T3ChatUsageError.noSessionCookie,
             CodexBarCore.T3ChatUsageError.invalidCredentials,
             CodexBarCore.VertexAIOAuthCredentialsError.missingTokens,
             CodexBarCore.VertexAIOAuthCredentialsError.missingClientCredentials,
             CodexBarCore.VertexAIFetchError.unauthorized,
             CodexBarCore.WarpUsageError.missingCredentials,
             CodexBarCore.WindsurfWebFetcherError.noSessionData,
             CodexBarCore.WindsurfWebFetcherError.invalidManualSession(_),
             CodexBarCore.ZedStatusProbeError.notSignedIn,
             CodexBarCore.ZedStatusProbeError.unauthorized,
             CodexBarCore.ZenMuxUsageError.notConfigured,
             CodexBarCore.ZenMuxUsageError.authenticationRejected,
             CodexBarCore.ZoomMateUsageError.noCapture,
             CodexBarCore.ZoomMateUsageError.noSession,
             CodexBarCore.ZoomMateUsageError.invalidCredentials,
             CodexBarCore.GroqConsoleError.missingSession:
            return .needsAuth
        case CodexBarCore.ElevenLabsUsageError.missingPermissions,
             CodexBarCore.ElevenLabsUsageError.accessDenied,
             CodexBarCore.GroqUsageError.accessDenied(_),
             CodexBarCore.GroqConsoleError.accessDenied(_),
             CodexBarCore.VertexAIFetchError.forbidden,
             CodexBarCore.OpenAIAPICreditBalanceError.forbidden:
            return permissions
        case CodexBarCore.AzureOpenAIUsageError.apiError(let status, _),
             CodexBarCore.OpenAIAPIUsageError.apiError(_, let status),
             CodexBarCore.WarpUsageError.apiError(let status, _),
             CodexBarCore.DoubaoUsageError.apiError(let status, _),
             CodexBarCore.WayfinderUsageError.apiError(let status),
             CodexBarCore.AiAndUsageError.apiError(let status),
             CodexBarCore.CodebuffUsageError.apiError(let status),
             CodexBarCore.FireworksUsageError.apiError(let status),
             CodexBarCore.IBMBobUsageError.apiError(let status),
             CodexBarCore.KiloUsageError.apiError(let status),
             CodexBarCore.OpenAIAPICreditBalanceError.apiError(let status),
             CodexBarCore.QoderUsageError.apiError(let status),
             CodexBarCore.SakanaUsageError.apiError(let status),
             CodexBarCore.ZenMuxUsageError.apiError(let status),
             CodexBarCore.ZedStatusProbeError.httpError(let status):
            return status == 401 ? .needsAuth : (status == 403 ? permissions : nil)
        default: return nil
        }
    }
}
